### ISSUE TITLE
classList.remove: test fails

### ISSUE THREAD

**Issue by monolithed** [eligrey/classList.js#38]
The latest test fails

http://jsbin.com/sitamaguso

Chrome, FF, Opera

**Comment by mislav** [comment]
It took me a while to understand what you're referencing in this issue. Please, next time it will save everybody time to be more specific by explaining your intention and what you've found in words. Thanks.

First thing that confused me was the fact that the test which you demonstrate as failing doesn't exist in the codebase in this repo as added by @eanakashima. That must mean you've added it yourself. Also, your test suite uses `el.testClassList` instead of `el.classList`. I presume that you've changed the property name to have the test suite exercise the actual code of the polyfill instead of falling back to the native `classList` implementation which most modern browsers now have. I think it's good that you did that because the test suite should definitely exercise the polyfill implementation. (That's the only way to be sure that the polyfill actually works.)

However, because you changed the polyfilled property name from `.classList` to `.testClassList`, you might have accidentally broken the implementation. I'm just speculating here. Or, you might have uncovered an actual bug in `remove()` polyfill. We would have to look at the actual unchanged source from this repo to be sure.

**Comment by mislav** [comment]
Oh, I apologize. Now I see that it was me who added that test in a separate `remove.js` file in 131fec3652e62f7bbf24049582f34b67d3fdf01f. I was only looking at `tests.js` previously. Looking into.

**Comment by monolithed** [comment]
> Also, your test suite uses el.testClassList instead of el.classList. I presume that you've changed the property name to have the test suite exercise the actual code of the polyfill instead of falling back to the native classList implementation which most modern browsers now have. I think it's good that you did that because the test suite should definitely exercise the polyfill implementation. (That's the only way to be sure that the polyfill actually works.)

I don't see no other way to test the one.

> Or, you might have uncovered an actual bug in remove() polyfill. 
PhantomJS uses WebKit-bases environment. I don't believe this dummy tests.
